Repository api-platform/core, pull requests merged in 2018-04, with the labels that each got.

#1786 Allow a POST request to have an empty body
  src/EventListener/DeserializeListener.php
  tests/EventListener/DeserializeListenerTest.php
Labels: enhancement

#1478 Improve ":id" param normalization
  .travis.yml
  composer.json
  features/bootstrap/FeatureContext.php
  features/main/uuid.feature
  src/Bridge/Doctrine/Orm/ItemDataProvider.php
  src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
  src/Bridge/Doctrine/Orm/Util/IdentifierManagerTrait.php
  src/Bridge/RamseyUuid/Identifier/Normalizer/UuidNormalizer.php
  src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
  src/Bridge/Symfony/Bundle/Resources/config/api.xml
  src/Bridge/Symfony/Routing/IriConverter.php
  src/DataProvider/ItemDataProviderInterface.php
  src/EventListener/ReadListener.php
  src/Exception/InvalidIdentifierException.php
  src/Identifier/CompositeIdentifierParser.php
  src/Identifier/Normalizer/ChainIdentifierNormalizer.php
  src/Identifier/Normalizer/DateTimeIdentifierNormalizer.php
  tests/Bridge/Doctrine/Orm/ItemDataProviderTest.php
  tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
  tests/Bridge/Doctrine/Orm/Util/IdentifierManagerTraitTest.php
  tests/Bridge/RamseyUuid/Normalizer/UuidNormalizerTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Bridge/Symfony/Routing/IriConverterTest.php
  tests/EventListener/ReadListenerTest.php
  tests/Fixtures/TestBundle/DataProvider/ContainNonResourceItemDataProvider.php
  tests/Fixtures/TestBundle/Entity/RamseyUuidDummy.php
  tests/Fixtures/app/config/config_mysql.yml
  tests/Fixtures/app/config/config_postgres.yml
  tests/Fixtures/app/config/config_test.yml
  tests/Identifier/CompositeIdentifierParserTest.php
  tests/Identifier/Normalizer/ChainIdentifierNormalizerTest.php
Labels: [RFR] Ready for Review

#1814 Remove Brigade
  .travis.yml
  Dockerfile.coverage
  brigade.js
Labels: [RFR] Ready for Review

#1836 Speed-up Travis
  .travis.yml
  behat.yml.dist
  phpunit.xml.dist
  tests/Fixtures/app/AppKernel.php
  tests/Fixtures/app/config/config_test_phpunit.yml
Labels: [RFR] Ready for Review

#1841 Remove Brigade on 2.1
  Dockerfile.coverage
  brigade.js
  phpstan.neon
Labels: Ready

#1847 Change default priority on autoconfiguration Doctrine DataProvider extensions
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
Labels: [RFR] Ready for Review

#1830 Implement ability to define the controller for a subresource
  src/Bridge/Symfony/Routing/ApiLoader.php
  src/Operation/Factory/SubresourceOperationFactory.php
  tests/Bridge/Symfony/Routing/ApiLoaderTest.php
Labels: Ready

#1853 Fix the Behat test suite with low dependencies
  composer.json
Labels: Ready

#1863 [GraphQL] Add totalCount field for paginated collections
  features/graphql/collection.feature
  src/GraphQl/Resolver/Factory/CollectionResolverFactory.php
  src/GraphQl/Type/SchemaBuilder.php
  tests/GraphQl/Resolver/Factory/CollectionResolverFactoryTest.php
  tests/GraphQl/Type/SchemaBuilderTest.php
Labels: GraphQL, [WIP] Work In Progress

#1875 Enable item route on collection subresources
  features/main/subresource.feature
  src/Bridge/Doctrine/Orm/SubresourceDataProvider.php
  src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php
  src/Operation/Factory/SubresourceOperationFactory.php
  tests/Bridge/Doctrine/Orm/SubresourceDataProviderTest.php
  tests/Fixtures/TestBundle/Entity/RelatedDummy.php
  tests/Operation/Factory/SubresourceOperationFactoryTest.php
Labels: [RFR] Ready for Review

#1874 Forward operation name in the iri converter
  src/Bridge/Symfony/Routing/IriConverter.php
  tests/Bridge/Symfony/Routing/IriConverterTest.php
Labels: [RFR] Ready for Review, bug

#1877 Allow subresource items in the iri converter
  features/bootstrap/FeatureContext.php
  features/main/subresource.feature
  src/Bridge/Symfony/Bundle/Resources/config/api.xml
  src/Bridge/Symfony/Routing/IriConverter.php
  src/DataProvider/OperationDataProviderTrait.php
  src/EventListener/ReadListener.php
  src/Util/AttributesExtractor.php
  src/Util/RequestAttributesExtractor.php
  tests/Bridge/Symfony/Bundle/DataCollector/RequestDataCollectorTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Bridge/Symfony/Routing/IriConverterTest.php
  tests/EventListener/ReadListenerTest.php
Labels: [RFR] Ready for Review
