Repository api-platform/core, pull requests merged in 2018-05, with the labels that each got.

#1886 [GraphQL] Fix introspection (graphql-php / GraphiQL)
  composer.json
  features/bootstrap/GraphqlContext.php
  features/graphql/introspection.feature
  features/graphql/mutation.feature
  src/GraphQl/Type/Definition/InputUnionType.php
  src/GraphQl/Type/SchemaBuilder.php
  tests/GraphQl/Type/Definition/InputUnionTypeTest.php
Labels: GraphQL

#1855 Fix relations denormalization with plain ids
  features/main/relation.feature
  src/Exception/InvalidValueException.php
  src/Serializer/AbstractItemNormalizer.php
Labels: [RFR] Ready for Review

#1967 Allow DataPersister to return a new instance instead of mutating
  src/Bridge/Doctrine/Common/DataPersister.php
  src/DataPersister/ChainDataPersister.php
  src/DataPersister/DataPersisterInterface.php
  src/EventListener/WriteListener.php
  src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
  tests/Bridge/Doctrine/Common/DataPersisterTest.php
  tests/EventListener/WriteListenerTest.php
Labels: enhancement
