Repository api-platform/core, pull requests merged in 2019-12, with the labels that each got.

#1723 More query parameter validation (follow #1692)
  features/filter/filter_validation.feature
  src/Bridge/Symfony/Bundle/Resources/config/validator.xml
  src/Bridge/Symfony/Validator/Validator.php
  src/EventListener/QueryParameterValidateListener.php
  src/Filter/QueryParameterValidateListener.php
  src/Filter/QueryParameterValidator.php
  src/Filter/Validator/ArrayItems.php
  src/Filter/Validator/Bounds.php
  src/Filter/Validator/Enum.php
  src/Filter/Validator/Length.php
  src/Filter/Validator/MultipleOf.php
  src/Filter/Validator/Pattern.php
  src/Filter/Validator/Required.php
  src/Filter/Validator/ValidatorInterface.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/EventListener/QueryParameterValidateListenerTest.php
  tests/Filter/QueryParameterValidatorTest.php
  tests/Filter/Validator/ArrayItemsTest.php
  tests/Filter/Validator/BoundsTest.php
  tests/Filter/Validator/EnumTest.php
  tests/Filter/Validator/LengthTest.php
  tests/Filter/Validator/MultipleOfTest.php
  tests/Filter/Validator/PatternTest.php
  tests/Filter/Validator/RequiredTest.php
  tests/Fixtures/TestBundle/Document/FilterValidator.php
  tests/Fixtures/TestBundle/Entity/FilterValidator.php
  tests/Fixtures/TestBundle/Filter/ArrayItemsFilter.php
  tests/Fixtures/TestBundle/Filter/BoundsFilter.php
  tests/Fixtures/TestBundle/Filter/EnumFilter.php
  tests/Fixtures/TestBundle/Filter/LengthFilter.php
  tests/Fixtures/TestBundle/Filter/MultipleOfFilter.php
  tests/Fixtures/TestBundle/Filter/PatternFilter.php
  tests/Fixtures/TestBundle/Filter/RequiredAllowEmptyFilter.php
  tests/Fixtures/app/config/config_common.yml
Labels: [RFR] Ready for Review

#3309 Fix JSON Schema generation for non-resource class
  src/Bridge/Symfony/Bundle/Resources/config/json_schema.xml
  src/Hydra/JsonSchema/SchemaFactory.php
  src/JsonSchema/SchemaFactory.php
  src/JsonSchema/SchemaFactoryInterface.php
  src/JsonSchema/TypeFactory.php
  src/JsonSchema/TypeFactoryInterface.php
  tests/JsonSchema/SchemaFactoryTest.php
Labels: OpenAPI

#3327 [GraphQL] Better detection of collection types
  src/GraphQl/Type/TypeBuilder.php
  tests/GraphQl/Type/TypeBuilderTest.php
Labels: GraphQL

#3328 [GraphQL] Fix getGraphQlPaginationType when not a resource
  src/DataProvider/Pagination.php
Labels: GraphQL
