Repository api-platform/core, pull requests merged in 2019-05, with the labels that each got.

#2703 Removed hard dependencies on doctrine odm to run the tests
  .circleci/config.yml
  .travis.yml
  composer.json
  phpunit.mongo.xml
  phpunit.xml.dist
  tests/Bridge/Doctrine/Common/Util/IdentifierManagerTraitTest.php
  tests/Bridge/Doctrine/MongoDbOdm/CollectionDataProviderTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Extension/FilterExtensionTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Extension/OrderExtensionTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/BooleanFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/DateFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/ExistsFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/NumericFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/RangeFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/ItemDataProviderTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Metadata/Property/DoctrineMongoDbOdmPropertyMetadataFactoryTest.php
  tests/Bridge/Doctrine/MongoDbOdm/PaginatorTest.php
  tests/Bridge/Doctrine/MongoDbOdm/PropertyInfo/DoctrineExtractorTest.php
  tests/Bridge/Doctrine/MongoDbOdm/SubresourceDataProviderTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
  tests/Bridge/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
  tests/Fixtures/app/config/config_common.yml
  tests/Fixtures/app/config/config_mongodb.yml
  tests/Fixtures/app/config/config_services_mongodb.yml
  tests/Fixtures/app/config/config_test_mongodb.yml
  tests/Fixtures/app/config/routing_mongodb.yml
  tests/Fixtures/app/config/routing_test_mongodb.yml
Labels: ⭐ EU-FOSSA Hackathon

#2709 Use the metadata aware name converter when available fix #2677
  composer.json
  src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPass.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php
  tests/Fixtures/Elasticsearch/Fixtures/tweet.json
  tests/Fixtures/Elasticsearch/Fixtures/user.json
  tests/Fixtures/Elasticsearch/Mappings/tweet.json
  tests/Fixtures/Elasticsearch/Mappings/user.json
  tests/Fixtures/app/config/config_elasticsearch.yml
Labels: ⭐ EU-FOSSA Hackathon

#2751 Add support for name converter in filters
  features/bootstrap/DoctrineContext.php
  features/doctrine/boolean_filter.feature
  features/doctrine/date_filter.feature
  features/doctrine/exists_filter.feature
  features/doctrine/numeric_filter.feature
  features/doctrine/order_filter.feature
  features/doctrine/range_filter.feature
  features/doctrine/search_filter.feature
  features/filter/property_filter.feature
  features/hal/collection.feature
  features/jsonapi/related-resouces-inclusion.feature
  features/main/crud.feature
  features/serializer/property_filter.feature
  phpstan.neon.dist
  src/Bridge/Doctrine/Common/Filter/BooleanFilterTrait.php
  src/Bridge/Doctrine/Common/Filter/DateFilterTrait.php
  src/Bridge/Doctrine/Common/Filter/ExistsFilterTrait.php
  src/Bridge/Doctrine/Common/Filter/NumericFilterTrait.php
  src/Bridge/Doctrine/Common/Filter/OrderFilterTrait.php
  src/Bridge/Doctrine/Common/Filter/RangeFilterTrait.php
  src/Bridge/Doctrine/Common/Filter/SearchFilterTrait.php
  src/Bridge/Doctrine/MongoDbOdm/Filter/AbstractFilter.php
  src/Bridge/Doctrine/MongoDbOdm/Filter/ExistsFilter.php
  src/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilter.php
  src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
  src/Bridge/Doctrine/Orm/Filter/AbstractContextAwareFilter.php
  src/Bridge/Doctrine/Orm/Filter/AbstractFilter.php
  src/Bridge/Doctrine/Orm/Filter/ExistsFilter.php
  src/Bridge/Doctrine/Orm/Filter/OrderFilter.php
  src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
  src/Bridge/Symfony/Bundle/Resources/config/api.xml
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
  src/Serializer/Filter/PropertyFilter.php
  tests/Bridge/Doctrine/Common/Filter/SearchFilterTestTrait.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/OrderFilterTest.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
  tests/Bridge/Doctrine/Orm/Filter/ExistsFilterTest.php
  tests/Bridge/Doctrine/Orm/Filter/OrderFilterTest.php
  tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
  tests/Fixtures/TestBundle/Document/ConvertedBoolean.php
  tests/Fixtures/TestBundle/Document/ConvertedDate.php
  tests/Fixtures/TestBundle/Document/ConvertedInteger.php
  tests/Fixtures/TestBundle/Document/ConvertedString.php
  tests/Fixtures/TestBundle/Document/DummyProperty.php
  tests/Fixtures/TestBundle/Entity/ConvertedBoolean.php
  tests/Fixtures/TestBundle/Entity/ConvertedDate.php
  tests/Fixtures/TestBundle/Entity/ConvertedInteger.php
  tests/Fixtures/TestBundle/Entity/ConvertedString.php
  tests/Fixtures/TestBundle/Entity/DummyProperty.php
  tests/Fixtures/app/config/config_common.yml
  tests/Fixtures/app/config/config_orm.yml
  tests/Fixtures/app/config/config_services_mongodb.yml
  tests/Serializer/Filter/PropertyFilterTest.php
Labels: Ready

#2772 [GraphQL] Services Refactoring
  features/graphql/collection.feature
  features/graphql/filters.feature
  features/graphql/mutation.feature
  features/graphql/type.feature
  phpstan.neon.dist
  src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
  src/GraphQl/Type/FieldsBuilder.php
  src/GraphQl/Type/FieldsBuilderInterface.php
  src/GraphQl/Type/SchemaBuilder.php
  src/GraphQl/Type/TypeBuilder.php
  src/GraphQl/Type/TypeBuilderInterface.php
  src/GraphQl/Type/TypeConverter.php
  src/GraphQl/Type/TypeConverterInterface.php
  src/GraphQl/Type/TypeNotFoundException.php
  src/GraphQl/Type/TypesContainer.php
  src/GraphQl/Type/TypesContainerInterface.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Fixtures/TestBundle/GraphQl/Type/Definition/DateTimeType.php
  tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php
  tests/Fixtures/app/config/config_common.yml
  tests/GraphQl/Type/FieldsBuilderTest.php
  tests/GraphQl/Type/SchemaBuilderTest.php
  tests/GraphQl/Type/TypeBuilderTest.php
  tests/GraphQl/Type/TypeConverterTest.php
  tests/GraphQl/Type/TypesContainerTest.php
Labels: GraphQL

#2776 Update CircleCI config
  .circleci/config.yml
  .gitignore
  .travis.yml
  behat.yml.dist
  features/bootstrap/CoverageContext.php
  phpunit_mongodb.xml
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
Labels: [RFR] Ready for Review

#2815 Add a note in the CHANGELOG about empty request content bugfix
  CHANGELOG.md
Labels: [RFR] Ready for Review

#2817 Fix BC break in AbstractItemNormalizer introduced in v2.4
  src/GraphQl/Serializer/ItemNormalizer.php
  src/Hal/Serializer/ItemNormalizer.php
  src/JsonApi/Serializer/ItemNormalizer.php
  src/JsonLd/Serializer/ItemNormalizer.php
  src/Serializer/AbstractItemNormalizer.php
Labels: bug
