Repository api-platform/core, pull requests merged in 2019-06, with the labels that each got.

#2843 Don't try to mock UnitOfWork as it's final
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  composer.json
  tests/Bridge/Doctrine/MongoDbOdm/Extension/PaginationExtensionTest.php
  tests/Bridge/Doctrine/MongoDbOdm/PaginatorTest.php
  tests/Fixtures/app/bootstrap.php
  tests/Fixtures/app/config/config_common.yml
Labels: [RFR] Ready for Review

#2822 Fix serialization when using interface as resource
  .editorconfig
  composer.json
  features/bootstrap/DoctrineContext.php
  features/jsonld/interface_as_resource.feature
  features/main/relation.feature
  phpstan.neon.dist
  src/Api/ResourceClassResolver.php
  src/Bridge/Symfony/Bundle/Resources/config/metadata/metadata.xml
  src/Hydra/Serializer/DocumentationNormalizer.php
  src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
  src/Util/ReflectionClassRecursiveIterator.php
  tests/Api/IdentifiersExtractorTest.php
  tests/Fixtures/TestBundle/DataProvider/ProductDocumentItemDataProvider.php
  tests/Fixtures/TestBundle/DataProvider/ProductItemDataProvider.php
  tests/Fixtures/TestBundle/DataProvider/ResourceInterfaceImplementationDataProvider.php
  tests/Fixtures/TestBundle/DataProvider/TaxonDocumentItemDataProvider.php
  tests/Fixtures/TestBundle/DataProvider/TaxonItemDataProvider.php
  tests/Fixtures/TestBundle/Document/Product.php
  tests/Fixtures/TestBundle/Document/Taxon.php
  tests/Fixtures/TestBundle/Entity/Product.php
  tests/Fixtures/TestBundle/Entity/Taxon.php
  tests/Fixtures/TestBundle/Model/ProductInterface.php
  tests/Fixtures/TestBundle/Model/ResourceBarInterface.php
  tests/Fixtures/TestBundle/Model/ResourceInterface.php
  tests/Fixtures/TestBundle/Model/ResourceInterfaceImplementation.php
  tests/Fixtures/TestBundle/Model/TaxonInterface.php
  tests/Fixtures/TestBundle/Resources/config/api_resources.yml
  tests/Fixtures/TestBundle/Resources/config/api_resources/my_resource.yml
  tests/Fixtures/app/config/api_platform_mongodb_odm/resources.yaml
  tests/Fixtures/app/config/api_platform_orm/resources.yaml
  tests/Fixtures/app/config/api_resources_mongodb_odm.yaml
  tests/Fixtures/app/config/api_resources_orm.yaml
  tests/Fixtures/app/config/config_mongodb.yml
  tests/Fixtures/app/config/config_orm.yml
  tests/Fixtures/app/config/config_test.yml
  tests/Metadata/Property/Factory/SerializerPropertyMetadataFactoryTest.php
Labels: [RFR] Ready for Review

#2784 Compatiblity with Symfony 4.3
  .travis.yml
  composer.json
  features/bootstrap/HydraContext.php
  features/graphql/mutation.feature
  features/hydra/docs.feature
  features/jsonld/context.feature
  phpstan.neon.dist
  src/Bridge/Doctrine/MongoDbOdm/PropertyInfo/DoctrineExtractor.php
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm_mercure_publisher.xml
  src/Bridge/Symfony/Bundle/Resources/config/messenger.xml
  src/Bridge/Symfony/Bundle/Resources/views/DataCollector/request.html.twig
  src/Bridge/Symfony/Messenger/DataPersister.php
  src/EventListener/ExceptionListener.php
  src/Serializer/AbstractItemNormalizer.php
  src/Serializer/ItemNormalizer.php
  tests/Bridge/Doctrine/MongoDbOdm/PropertyInfo/DoctrineExtractorTest.php
  tests/Bridge/Doctrine/MongoDbOdm/PropertyInfo/Fixtures/DoctrineGeneratedValue.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Bridge/Symfony/Messenger/DataPersisterTest.php
  tests/Fixtures/app/AppKernel.php
  tests/Fixtures/app/config/config_common.yml
Labels: [WIP] Work In Progress

#2824 [GraphQL] Resolve types in custom operations
  features/graphql/collection.feature
  features/graphql/mutation.feature
  features/graphql/query.feature
  src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
  src/GraphQl/Type/FieldsBuilder.php
  src/GraphQl/Type/FieldsBuilderInterface.php
  src/GraphQl/Type/TypeBuilder.php
  src/GraphQl/Type/TypeConverter.php
  src/GraphQl/Type/TypeConverterInterface.php
  tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
  tests/Fixtures/TestBundle/Document/DummyCustomQuery.php
  tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
  tests/Fixtures/TestBundle/Entity/DummyCustomQuery.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryCollectionResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryItemResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/SumMutationResolver.php
  tests/Fixtures/TestBundle/GraphQl/Type/Definition/DateTimeType.php
  tests/Fixtures/TestBundle/GraphQl/Type/TypeConverter.php
  tests/GraphQl/Type/FieldsBuilderTest.php
  tests/GraphQl/Type/TypeBuilderTest.php
  tests/GraphQl/Type/TypeConverterTest.php
Labels: GraphQL

#2859 Fixed denormalization of a constructor argument which is a collection of non-resources
  features/serializer/deserialize_objects_using_constructor.feature
  src/Serializer/AbstractItemNormalizer.php
  tests/Fixtures/TestBundle/Document/DummyEntityWithConstructor.php
  tests/Fixtures/TestBundle/Entity/DummyEntityWithConstructor.php
Labels: [RFR] Ready for Review, bug

#2861 Allow custom operations to return a different class than the expected resource class
  features/main/custom_operation.feature
  src/Hal/Serializer/ItemNormalizer.php
  src/JsonApi/Serializer/ItemNormalizer.php
  src/JsonLd/Serializer/ItemNormalizer.php
  src/Serializer/AbstractItemNormalizer.php
  tests/Fixtures/TestBundle/Controller/Payment/VoidPaymentAction.php
  tests/Fixtures/TestBundle/Document/Payment.php
  tests/Fixtures/TestBundle/Document/VoidPayment.php
  tests/Fixtures/TestBundle/Entity/Payment.php
  tests/Fixtures/TestBundle/Entity/VoidPayment.php
  tests/Fixtures/app/config/config_common.yml
  tests/GraphQl/Serializer/ItemNormalizerTest.php
  tests/Hal/Serializer/ItemNormalizerTest.php
  tests/Hydra/Serializer/CollectionFiltersNormalizerTest.php
  tests/Hydra/Serializer/CollectionNormalizerTest.php
  tests/JsonApi/Serializer/ItemNormalizerTest.php
  tests/JsonLd/Serializer/ItemNormalizerTest.php
  tests/Serializer/AbstractItemNormalizerTest.php
  tests/Serializer/ItemNormalizerTest.php
Labels: [RFR] Ready for Review, bug
