Repository api-platform/core, pull requests merged in 2019-04, with the labels that each got.

#2678 Fix BC break in Doctrine ORM OrderFilter
  src/Bridge/Doctrine/Common/Filter/OrderFilterTrait.php
Labels: bug

#2447 [GraphQL] Add custom mutations
  features/bootstrap/DoctrineContext.php
  features/graphql/mutation.feature
  phpstan.neon.dist
  src/Bridge/Symfony/Bundle/ApiPlatformBundle.php
  src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
  src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/GraphQlMutationResolverPass.php
  src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
  src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php
  src/GraphQl/Resolver/Factory/ItemResolverFactory.php
  src/GraphQl/Resolver/MutationResolverInterface.php
  tests/Bridge/Symfony/Bundle/ApiPlatformBundleTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Fixtures/TestBundle/Document/DummyCustomMutation.php
  tests/Fixtures/TestBundle/Entity/DummyCustomMutation.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryCollectionResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryItemResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNotRetrievedItemDocumentResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/DummyCustomQueryNotRetrievedItemResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/SumMutationResolver.php
  tests/Fixtures/TestBundle/GraphQl/Resolver/SumNotPersistedMutationResolver.php
  tests/Fixtures/app/config/config_common.yml
  tests/Fixtures/app/config/config_orm.yml
  tests/Fixtures/app/config/config_services_mongodb.yml
  tests/GraphQl/Resolver/Factory/ItemMutationResolverFactoryTest.php
  tests/GraphQl/Resolver/Factory/ItemResolverFactoryTest.php
Labels: GraphQL

#2680 fix: update symfony/serializer required version
  composer.json
  phpstan.neon.dist
Labels: [WFC] Waiting for Change

#2679 Normalize non-resource objects in a standalone normalizer
  .circleci/config.yml
  .travis.yml
  appveyor.yml
  features/bootstrap/JsonContext.php
  features/doctrine/search_filter.feature
  features/graphql/input_output.feature
  features/graphql/mutation.feature
  features/graphql/non_resource.feature
  features/hal/non_resource.feature
  features/jsonapi/non_resource.feature
  features/jsonapi/related-resouces-inclusion.feature
  features/jsonld/input_output.feature
  features/jsonld/non_resource.feature
  features/main/non_resource.feature
  src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php
  src/Bridge/Symfony/Bundle/Resources/config/api.xml
  src/Bridge/Symfony/Bundle/Resources/config/elasticsearch.xml
  src/Bridge/Symfony/Bundle/Resources/config/graphql.xml
  src/Bridge/Symfony/Bundle/Resources/config/hal.xml
  src/Bridge/Symfony/Bundle/Resources/config/jsonapi.xml
  src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml
  src/GraphQl/Serializer/ItemNormalizer.php
  src/GraphQl/Serializer/ObjectNormalizer.php
  src/Hal/Serializer/ItemNormalizer.php
  src/Hal/Serializer/ObjectNormalizer.php
  src/JsonApi/Serializer/ItemNormalizer.php
  src/JsonApi/Serializer/ObjectNormalizer.php
  src/JsonLd/Serializer/ItemNormalizer.php
  src/JsonLd/Serializer/ObjectNormalizer.php
  src/Serializer/AbstractItemNormalizer.php
  src/Serializer/ItemNormalizer.php
  src/Serializer/NoOpScalarNormalizer.php
  tests/Bridge/Elasticsearch/Serializer/ItemNormalizerTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Fixtures/NotAResource.php
  tests/Fixtures/TestBundle/Document/ContainNonResource.php
  tests/Fixtures/TestBundle/Document/RelatedDummy.php
  tests/Fixtures/TestBundle/Entity/ContainNonResource.php
  tests/Fixtures/TestBundle/Entity/PlainObjectDummy.php
  tests/Fixtures/TestBundle/Entity/RelatedDummy.php
  tests/GraphQl/Serializer/ItemNormalizerTest.php
  tests/Hal/Serializer/ItemNormalizerTest.php
  tests/JsonApi/Serializer/ItemNormalizerTest.php
  tests/JsonLd/Serializer/ItemNormalizerTest.php
  tests/Serializer/AbstractItemNormalizerTest.php
  tests/Serializer/ItemNormalizerTest.php
Labels: bug

#2188 Add Behat test for PR 2183
  features/bootstrap/DoctrineContext.php
  features/main/relation.feature
  tests/Fixtures/TestBundle/Document/Address.php
  tests/Fixtures/TestBundle/Document/Customer.php
  tests/Fixtures/TestBundle/Document/Order.php
  tests/Fixtures/TestBundle/Entity/Address.php
  tests/Fixtures/TestBundle/Entity/Customer.php
  tests/Fixtures/TestBundle/Entity/Order.php
Labels: EU-FOSSA Hackathon

#2698 Added support for pagination parameters in subresource docs
  features/openapi/docs.feature
  features/swagger/docs.feature
  src/Swagger/Serializer/DocumentationNormalizer.php
Labels: EU-FOSSA Hackathon

#2086 Ignore property that does not exist for interfaces (identifiers for interfaces)
  features/main/table_inheritance.feature
  src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php
  tests/Fixtures/FileConfigurations/interface_resource.yml
  tests/Fixtures/TestBundle/DataProvider/ResourceInterfaceImplementationDataProvider.php
  tests/Fixtures/TestBundle/OtherResources/ResourceInterface.php
  tests/Fixtures/TestBundle/OtherResources/ResourceInterfaceImplementation.php
  tests/Fixtures/TestBundle/Resources/config/api_resources.yml
  tests/Metadata/Property/Factory/ExtractorPropertyMetadataFactoryTest.php
Labels: EU-FOSSA Hackathon

#2697 fix (cache): prevent avoidable purge
  src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php
  tests/Bridge/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
  tests/Fixtures/TestBundle/Entity/DummyNoGetOperation.php
Labels: EU-FOSSA Hackathon

#2699 Added an additional test for strict types validation
  features/security/strong_typing.feature
  tests/Fixtures/TestBundle/Entity/Dummy.php
Labels: EU-FOSSA Hackathon

#1974 Be more intelligent in determining property writable/readable link.
  php-cs-fixer.phar
  src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php
  tests/Fixtures/TestBundle/Document/CustomNormalizedDummy.php
  tests/Fixtures/TestBundle/Entity/CustomNormalizedDummy.php
Labels: EU-FOSSA Hackathon

#1844 feature: improve ids management for association and fix invalid iri/uuid in SearchFilter
  features/doctrine/search_filter.feature
  src/Bridge/Doctrine/Common/Filter/SearchFilterTrait.php
  src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php
  src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
  src/Bridge/Symfony/Bundle/Resources/config/api.xml
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
  src/Test/DoctrineMongoDbOdmFilterTestCase.php
  tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php
  tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Fixtures/TestBundle/Document/DummyCar.php
  tests/Fixtures/TestBundle/Entity/DummyCar.php
  tests/Util/AnnotationFilterExtractorTraitTest.php
Labels: EU-FOSSA Hackathon, [RFR] Ready for Review

#2702 Fix typos
  features/doctrine/search_filter.feature
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml
  src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml
Labels: EU-FOSSA Hackathon

#2705 Test input messenger with MongoDB
  features/graphql/input_output.feature
  tests/Fixtures/TestBundle/Document/MessengerWithInput.php
  tests/Fixtures/TestBundle/MessengerHandler/Document/MessengerWithInputHandler.php
  tests/Fixtures/TestBundle/MessengerHandler/Entity/MessengerWithInputHandler.php
  tests/Fixtures/app/config/config_common.yml
  tests/Fixtures/app/config/config_orm.yml
  tests/Fixtures/app/config/config_services_mongodb.yml
Labels: MongoDB

#2707 Better contributing documentation
  CONTRIBUTING.md
Labels: EU-FOSSA Hackathon

#2721 Refactor the bundle configuration and extension
  composer.json
  src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php
  src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ConfigurationTest.php
Labels: [RFR] Ready for Review

#2713 Fix error message in identifiers extractor
  src/Api/IdentifiersExtractor.php
  tests/Api/IdentifiersExtractorTest.php
  tests/Bridge/Symfony/Routing/IriConverterTest.php
Labels: ⭐ EU-FOSSA Hackathon

#2744 Fix HTTP status code when output class is set to null
  features/jsonld/input_output.feature
  phpstan.neon.dist
  src/EventListener/SerializeListener.php
  src/Metadata/Resource/Factory/InputOutputResourceMetadataFactory.php
  src/Swagger/Serializer/DocumentationNormalizer.php
  tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php
  tests/EventListener/SerializeListenerTest.php
  tests/Fixtures/TestBundle/Controller/DummyDtoNoInput/CreateItemAction.php
  tests/Fixtures/TestBundle/Controller/DummyDtoNoInput/DoubleBatAction.php
  tests/Fixtures/TestBundle/DataTransformer/DummyDtoNoInputToOutputDtoDataTransformer.php
  tests/Fixtures/TestBundle/Document/DummyDtoNoInput.php
  tests/Fixtures/TestBundle/Entity/DummyDtoNoInput.php
  tests/Fixtures/app/config/config_common.yml
Labels: [RFR] Ready for Review
