Repository api-platform/core, pull requests merged in 2021-02, with the labels that each got.

#3985 Fix #3979 identifier chain not breaking after denormalizing
  src/Bridge/Symfony/Bundle/Resources/config/api.xml
  src/Bridge/Symfony/Bundle/Resources/config/ramsey_uuid.xml
  src/Identifier/IdentifierConverter.php
  tests/Identifier/IdentifierConverterTest.php
Labels: [RFR] Ready for Review

#3783 Add traversable paginator
  CHANGELOG.md
  src/DataProvider/TraversablePaginator.php
  tests/DataProvider/TraversablePaginatorTest.php
Labels: Ready, hacktoberfest-accepted

#3774 Handle binary UUID in SearchFilter
  .github/workflows/ci.yml
  CHANGELOG.md
  behat.yml.dist
  features/doctrine/search_filter.feature
  src/Bridge/Doctrine/Orm/Filter/SearchFilter.php
  tests/Behat/DoctrineContext.php
  tests/Bridge/Doctrine/Orm/Filter/SearchFilterTest.php
  tests/Fixtures/TestBundle/Entity/RamseyUuidBinaryDummy.php
  tests/Fixtures/app/config/config_common.yml
  tests/Fixtures/app/config/config_mysql.yml
  tests/Fixtures/app/config/config_postgres.yml
  tests/Fixtures/app/config/config_sqlite.yml
Labels: Ready
