Repository api-platform/core, pull requests merged in 2023-10, with the labels that each got.

#5864 fix(jsonschema): do not override nor complete ApiProperty::schema user value
  src/JsonSchema/SchemaFactory.php
  tests/Fixtures/TestBundle/Entity/Issue5793/BagOfTests.php
  tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php
Labels: bug

#5844 feat: improve `collectDenormalizationErrors`
  features/main/validation.feature
  src/JsonApi/Serializer/ItemNormalizer.php
  src/Serializer/AbstractItemNormalizer.php
  src/Serializer/Tests/AbstractItemNormalizerTest.php
Labels: enhancement

#5835 feat(elasticsearch): filtering on nested fields
  features/elasticsearch/match_filter.feature
  features/elasticsearch/read.feature
  src/Elasticsearch/Tests/Filter/MatchFilterTest.php
  src/Elasticsearch/Tests/Filter/TermFilterTest.php
  src/Elasticsearch/Tests/Util/FieldDatatypeTraitTest.php
  src/Elasticsearch/Util/FieldDatatypeTrait.php
  tests/Fixtures/Elasticsearch/Fixtures/book.json
  tests/Fixtures/Elasticsearch/Mappings/book.json
  tests/Fixtures/Elasticsearch/Model/Book.php
  tests/Fixtures/Elasticsearch/Model/Genre.php
  tests/Fixtures/Elasticsearch/Model/Library.php
Labels: enhancement

#5730 minor: remove reference to .woff fonts-format
  src/Symfony/Bundle/Resources/public/fonts/open-sans/400.css
  src/Symfony/Bundle/Resources/public/fonts/open-sans/700.css
Labels: stale

#5910 fix(graphql): item resolver inheritance error
  src/GraphQl/Resolver/Factory/ItemResolverFactory.php
  src/GraphQl/Tests/Fixtures/ApiResource/ChildFoo.php
  src/GraphQl/Tests/Fixtures/ApiResource/ParentFoo.php
  src/GraphQl/Tests/Resolver/Factory/ItemResolverFactoryTest.php
Labels: needs test, hacktoberfest-accepted

#5907 ci: fix PHPUNIT
  composer.json
  phpstan.neon.dist
  tests/Core/Bridge/Symfony/Bundle/Command/SwaggerCommandTest.php
  tests/Core/Bridge/Symfony/Maker/MakeDataPersisterTest.php
  tests/Core/Bridge/Symfony/Maker/MakeDataProviderTest.php
  tests/Doctrine/EventListener/PurgeHttpCacheListenerTest.php
  tests/Fixtures/Symfony/Maker/CustomStateProcessor.fixture
  tests/Fixtures/Symfony/Maker/CustomStateProviderPhp7.fixture
  tests/Fixtures/Symfony/Maker/CustomStateProviderPhp8.fixture
  tests/Fixtures/TestBundle/MessageHandler/PasswordResetRequestHandler.php
  tests/Fixtures/TestBundle/MessengerHandler/Document/MessengerWithInputHandler.php
  tests/Fixtures/TestBundle/MessengerHandler/Entity/MessengerWithInputHandler.php
  tests/Fixtures/TestBundle/MessengerHandler/MessengerWithResponseHandler.php
  tests/Fixtures/app/AppKernel.php
  tests/Fixtures/app/bootstrap.php
  tests/Metadata/Property/PropertyInfoPropertyNameCollectionFactoryTest.php
  tests/Symfony/Bundle/Test/WebTestCaseTest.php
  tests/Symfony/Bundle/Twig/ApiPlatformProfilerPanelTest.php
  tests/Symfony/Maker/MakeStateProcessorTest.php
  tests/Symfony/Maker/MakeStateProviderTest.php
Labels: hacktoberfest-accepted

#5906 ci: fix 2.7 PHPSTAN
  phpstan.neon.dist
  src/Core/GraphQl/Resolver/ResourceFieldResolver.php
  tests/Fixtures/TestBundle/Entity/Dummy.php
  tests/Fixtures/app/AppKernel.php
Labels: hacktoberfest-accepted
